version: '3.12'

services:
  food_shift_service:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    env_file:
      - .env
    ports:    
      - '27017:27017'
    volumes:
      - ./mongodata://c:/Program Files/MongoDB/Server/7.0/data

volumes:
  mongodata:

